# Generated by Django 5.2.15 on 2026-07-11 11:57

from django.db import migrations


def set_order_item_price(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    for item in OrderItem.objects.select_related('product').all():
        item.price = item.product.price
        item.save()


def reverse_set_order_item_price(app, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(set_order_item_price,
                             reverse_set_order_item_price)
    ]
