# Generated by Django 5.2.15 on 2026-07-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_alter_order_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_choice',
            field=models.CharField(choices=[('cash', 'Наличными'), ('card', 'Онлайн')], db_index=True, default='card', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
