# Generated by Django 5.2.15 on 2026-07-19 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_restaurant_latitude_restaurant_longitude'),
        ('places', '0002_alter_place_options_alter_place_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='longitude',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='place',
            field=models.OneToOneField(blank=True, help_text='Связь с моделью Place для хранения координат', null=True, on_delete=django.db.models.deletion.SET_NULL, to='places.place', verbose_name='местоположение'),
        ),
    ]
