# Generated by Django 5.2.15 on 2026-07-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_alter_order_pay_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Необработанный'), ('confirmed', 'Подтвержден'), ('cooking', 'Готовится'), ('delivering', 'В доставке'), ('completed', 'Выполнен')], db_index=True, default='created', max_length=20, verbose_name='Статус'),
        ),
    ]
