# Generated by Django 5.2.15 on 2026-07-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20260711_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Принят'), ('confirmed', 'Подтвержден'), ('cooking', 'Готовится'), ('delivering', 'В доставке'), ('completed', 'Выполнен')], db_index=True, default='created', max_length=20),
        ),
    ]
