# Generated by Django 5.2.15 on 2026-07-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_remove_restaurant_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_choice',
            field=models.CharField(choices=[('cash', 'Наличными'), ('card', 'Онлайн')], db_index=True, max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
