# Generated by Django 5.2.15 on 2026-07-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_alter_order_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='place',
        ),
    ]
